<?php if(!defined('HDPHP_PATH'))EXIT;
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('12','辞旧迎新，年末钜惠火爆来袭！最低的价格，参加业界最好的培训！','0','','100','','','1','admin','1390457881','1390414432','','','1','100','1','10','辞旧迎新，年末钜惠火爆来袭！最低的价格，参加业界最好的培训！','后盾PHP高薪就业班','2014年2月10号开年第一班火爆抢座中！后盾PHP高薪就业班实体，学期四个半月，即日起报名即可享受优惠，学费原价8800元，也可以办理0付费入学，就业后再还款。','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('13',' 后盾PHP高薪就业班支持零学费学习啦！详情请点击查看','0','','100','','','1','admin','1390458162','1390414881','','','1','100','1','10',' 后盾PHP高薪就业班支持零学费学习啦！详情请点击查看','学员,学习,后盾,开发,了解,商业,业内,完成,商城','即日起，后盾PHP高薪就业班支持学员零学费学习！业内最有含金量的课程体系！业内最牛的讲师亲自带课！你忍心错过吗？！ 学
习目标：后盾网php培训以实战项目为主，在讲解理论课时，大量实例同步进行，在学员毕业前要求每个学员独立完成MVC设计模式开发出完整的商业运营商城
及了解整套OA 
开发思路，学员经过后盾网底层开发深入学习了解后可以完成任何商业产品开发，如：团购、微博、论坛、物流管理、在线点','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('14','V5课堂火爆开课！超级大牛向军老师亲自坐镇！让整站开发变得前所未有之简单！','0','','100','','','1','admin','1390458305','1390415024','','','1','100','1','10','V5课堂火爆开课！超级大牛向军老师亲自坐镇！让整站开发变得前所未有之简单！','视频,内容,发布,盾友,后盾,最主,详细,要的,都以','年关将近，后盾网系列课程“V5课堂”给力开课！PHP业界超级大牛向军老师亲自带课每周进步一点点，让整站开发变得前所未有的简单！   众所周知，后盾网目前是国内原创视频最多的机构（不只在培训机构中），为广大IT爱好者提供了很好的自学的平台，视频质量高、内容讲解详细，最主要的是视频都以实例贯穿，得到了众多盾友的喜欢与好评。   当然视频发布的时间是不确定的，这样为盾友事先了解视频发布内容带来不便。为此','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('15','后盾网第一届电子竞技大赛成功举办！惊现小萝莉！【多图 让你一次看个够','0','','100','','','1','admin','1390458535','1390415272','','','1','100','1','10','后盾网第一届电子竞技大赛成功举办！惊现小萝莉！【多图 让你一次看个够','后盾,生活,本次,大家,小萝,季军队,惊现,军队,赛场','后盾网第一届电子竞技大赛于10月13在后盾网培训部召开，本次比赛旨在丰富同学们的课余生活，在紧张的学习生活中给大家送来一丝快乐。本次各路游戏精英齐聚，酣战淋漓，大呼过瘾！下面是精彩集锦，大家慢慢看哦~后盾网的话筒LOGO高端大气上档次给力的奖品哈哈，美女贺老师在给获奖队发奖~冠军队季军队赛场惊现小萝莉，话说这位可是来头不小，不仅是CF高手，而且.....凡是看过后盾网视频教程的都听过她的声音一字排','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('16','【最毒爆料，有最想见的老师】2013年后盾迎国庆暨第一届篮球友谊赛精彩剪辑','0','upload/content/2014/01/24/44621390545975.jpg','100','','','1','admin','1390458695','1390415440','','','1','100','1','10','【最毒爆料，有最想见的老师】2013年后盾迎国庆暨第一届篮球友谊赛精彩剪辑','全面,德智体,后盾,发展,中国,程序员,顶尖,围观,快来','视频比较长，但是其中亮点无数！哈哈，你懂的，快来围观吧！来后盾，做德智体全面发展的中国顶尖程序员！','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('17','【王牌课程】一元课堂再次开班啦！独立开发大型复杂静态页','0','upload/content/2014/01/24/46251390545948.jpg','100','','','1','admin','1390458998','1390415771','','','1','100','1','10','【王牌课程】一元课堂再次开班啦！独立开发大型复杂静态页','后盾,课堂,一元,开课,欣喜,备感,一期,成功,支持','本次一元课堂已顺利结课！下次开课请关注论坛通知。不吹嘘！不玩概念！让你体验真正的实战式教学模式！后盾独家高效率学习模式，完爆其他…，你懂的！请加入后盾网一元课堂2000人交流专群：77105752   后盾网自创办以来，一直坚持开放、共享的准则，几年来，广受大家的支持，备感欣喜。2013年6月份第一期一元课堂成功举办，无数盾友受益，此后很多没能参加的同学都在询问下期班何时开课，NOW，好消息来啦！','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('18','PHP业内权威专家讲师----向军 免费视频专版','0','upload/content/2014/01/23/64641390460037.jpg','100','','','1','admin','1390460048','1390415934','','','1','100','1','12','PHP业内权威专家讲师----向军 免费视频专版','视频,教程,免费,网页,织梦,软件下载,实例,使用,数据库','PHP业内权威专家讲师----向军 免费视频专版  PHP开发视频教程 Linux操作系统教程 Sphinx&amp;Coreseek中文分词 DIV+CSS网页布局 XHTML网页基础教程 HDPHP框架使用+实例视频 软件下载 DEDE织梦CMS教程 Mysql数据库视频教程 DreamWeaver CS5 smarty免费视频（公开课） DIV+CSS实战项目视频点击下载','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('19','后盾网原创免费视频(高质量教程，只有后盾网)','0','upload/content/2014/01/23/11811390460589.jpg','100','','','1','admin','1390460608','1390416867','','','1','100','1','12','后盾网原创免费视频(高质量教程，只有后盾网)','视频,教程,开发,使用,基于,实例,系统,后盾,实战','后盾网原创免费视频(高质量教程，只有后盾网)迅雷看看首页开发实战YII框架实例视频 CI框架使用视频豆瓣网前端首页实战开发许愿墙开发(基于HDPHP)博客系统开发（基于HDPHP）美团网开发(基于HDPHP) HTML5视频教程CSS3视频教程公益自学公开课高薪就业班课堂实录javascript ThinkPHP实例视频远程班培训实录视频HDjob招聘系统使用教程HDinfo 分类信息使用教程Li','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('20','后盾网VIP实战案例视频教程','0','upload/content/2014/01/23/21621390461210.jpg','100','','','1','admin','1390461217','1390417742','','','1','100','1','12','后盾网VIP实战案例视频教程','后盾,视频,以上,会员,折天,网论坛,赞助,优惠政策,签到','后盾网VIP实战案例视频教程内容分类及价格介绍优惠政策：为感谢长期以来一直关注后盾网论坛及与后盾一起成长的会员，特设签到会员办理优惠政策，
后盾网论坛签到会员优惠赞助办理VIP会员及单项目赞助标准：30天以上9.5折100天以上9折200天以上8折300天以上7折400天以上5折关于后盾视频：后盾网录制原创高清免费视频教程目前近500余课，更多提高版视频还在不断更新中，后盾网所有实战视频共40季','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('21','后盾求职招聘系统','0','upload/content/2014/01/23/64101390462154.jpg','100','','','1','admin','1390462111','1390418460','','','1','100','1','13','后盾求职招聘系统','缓存,模板,快速,机制,静态,文件,响应,界面,城市','MVC模式采用MVC设计模式二次开发快速、代码清晰数据缓存、节省资源多种缓存机制，文件缓存、模版缓存、静态缓存，加快响应多城市站点专题城市招聘,职位更加清晰多模板风格采用HD模板引擎多种缓存机制，文件缓存、模版缓存、静态缓存，加快响应快速定制出企业、简历模板自定义字段轻松添加资料收集表单快速搭建出前台界面界面美观、功能强大使用DIV+CSS布局页面后台众多管理功能','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('22','后盾分类信息管理系统','0','upload/content/2014/01/23/31701390462569.png','100','','','1','admin','1390462624','1390419229','','','1','100','1','13','后盾分类信息管理系统','自定义,类信息,模型,信息系统,一个,分类,字段,后盾,用户','后盾分类信息管理系统只为让你建站更简单更快速后盾HDinfo分类信息系统是一个基于HDPHP框架开发的分类信息CMS系统，简单的操作，齐全的功能，即便不懂PHP程序语言也能轻轻松松的打造出一个属于自己的全方位的分类信息网站灵活的自定义模型与自定义字段不配备任务系统模型，用户可以自由的添加删除让自己满意的自定义模型与自定义字段，创建设出各种各样的分类信息，操作简单，灵活性强，让创建不再受约束，让有强','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('23','HDCMS内容管理系统','0','upload/content/2014/01/23/19061390463259.png','100','','','1','admin','1390463266','1390419761','','','1','100','1','13','HDCMS内容管理系统','数据,框架,验证,表单,机制,处理,开源,自动,供强','基于HDPHP开源框架 HDPHP框架供强大的、完整的类库包,满足开发中的项目需求,可以将需要完成的任务代码量最小化，大大提高项目开发效率与质量。高效的核心编译处理机制让系统运行更快。安全可靠 COOKIE加密处理， 数据预处理机制， XSS安全防护， 表单自动验证， 强制数据类型转换， 输入数据过滤， 表单令牌验证， 防SQL注入， 图像上传检测。免费、开源HDPHP框架产品与HDCMS内容管理','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('24','PHP高薪就业班','0','upload/content/2014/01/23/45101390463445.gif','100','','','1','admin','1390463460','1390420130','','','1','100','1','14','PHP高薪就业班','优化,静态,网页,布局,掌握,标准化,阶段,教学内容,标记','培训周期：4个半月教学内容：从基础知识讲起，涵盖大型门户seo优化、web安全、mysql深度优化、索引优化、查询优化、php缓存优化、页面静态技术、memcache等后盾独家教学内容。【第一阶段:网页标准化布局】☆点击查看该阶段详细课程☆掌握HTML超文本标记语言，DIVCSS网页标准化布局，兼容多种浏览器独立设计制作静态网站，掌握用DIV+CSS方式制作网站的相关知识，PSD|JPG|PNG等','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('25','PHP高级工程师班','0','upload/content/2014/01/23/57811390463547.gif','100','','','1','admin','1390463569','1390420286','','','1','100','1','14','PHP高级工程师班','详细,课程,学员,讲解,开发,知识,数据库,阶段,安全','培训周期：3个半月教学内容：针对有一定前端WEB知识的学员，着重讲解PHP开发、MYSQL、LINUX操作系统等知识，并有后盾独家精髓内容课程，使学员快速达到独立开发的水平。【第一阶段:MYSQL工程师】☆点击查看该阶段详细课程☆MySQL做为优秀的关系型数据库管理系统拥有安全、体积小、速度快、成本低、开放源码等良好的特性。通过这部份课程详细讲解MYSQL安装、配置、数据库与表创建的详细设置。MY','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('26','PHP周末班','0','upload/content/2014/01/23/94041390463620.gif','100','','','1','admin','1390463631','1390420390','','','1','100','1','14','PHP周末班','阶段,网页,掌握,布局,制作,标准化,培训,浏览器,设计制作','培训周期：4个半月教学内容：有些同学还在工作，不能安排时间进行系统的PHP培训。特别开设周末班，方便大家掌握PHP开发。【第一阶段:网页标准化布局】☆点击查看该阶段详细课程☆掌握HTML超文本标记语言，DIVCSS网页标准化布局，兼容多种浏览器独立设计制作静态网站，掌握用DIV+CSS方式制作网站的相关知识，PSD|JPG|PNG等网页美工图的切图切片、CSS布局、前台CSS制作。【第二阶段:Ja','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('27','WEB前端开发工程师班','0','upload/content/2014/01/23/62821390463693.gif','100','','','1','admin','1390463701','1390420455','','','1','100','1','14','WEB前端开发工程师班','布局,阶段,网页,标准化,制作,掌握,前端,知识,网站','培训周期：35天教学内容：前端HTML知识，DivCss标准化页面布局以及前端脚本JAVASCRIPT的开发学习。【第一阶段:网页标准化布局】☆点击查看该阶段详细课程☆掌握HTML超文本标记语言，DIVCSS网页标准化布局，兼容多种浏览器独立设计制作静态网站，掌握用DIV+CSS方式制作网站的相关知识，PSD|JPG|PNG等网页美工图的切图切片、CSS布局、前台CSS制作。【第二阶段:JavaS','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('28','PHP远程班','0','upload/content/2014/01/23/23961390463825.gif','100','','','1','admin','1390463833','1390420523','#f00f00','','1','100','1','14','PHP远程班','网页,阶段,标准化,布局,掌握,知识,课程,远程,语言','培训周期：5个半月教学内容：PHP远程班专为不能来进行脱产学习的同学开设，提供最全面的远程授课系统，所讲知识与脱产培训班保持一致，并有后盾独家精髓内容课程。【第一阶段:网页标准化布局】☆点击查看该阶段详细课程☆掌握HTML超文本标记语言，DIVCSS网页标准化布局，兼容多种浏览器独立设计制作静态网站，掌握用DIV+CSS方式制作网站的相关知识，PSD|JPG|PNG等网页美工图的切图切片、CSS布','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('29','sdf','0','','100','','','1','admin','1390537977','1390537973','','','1','100','1','13','','','sdfsdfsdfdsf','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('30','sdf','0','','100','','','1','admin','1390537987','1390537984','','','1','100','1','13','','','sdfsfd','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('31','sdf','0','','100','','','1','admin','1390538453','1390537984','','','1','100','1','13','','','sdfsfddssdf','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`author`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`state`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('32','sdfsdf','0','','100','','','1','admin','1390538575','1390538572','','','1','100','1','13','','','dsfsdsdf','')");
