<?php if(!defined('HDPHP_PATH'))EXIT;
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('1','台称大陆潜艇技术获革命性飞跃 或已建造039C','0','upload/Content/2013/12/23/84841387741966.jpg','100','','','1','admin','1387741964','1387741805','#f00f00','','1','0','1','2','','我军,新一代,常规,潜艇,目前,主力,作战,建和,服役','　　我军新一代常规潜艇039B，该潜艇目前为我军的主力作战艇，目前在建和服役合计超过10艘。图片来源：鼎盛军事       　
　【环球网综合报道】台湾“中央社”12月20日报道称，大陆潜艇技术在最近十年来获得历史性提高，新一代潜艇采用了新型壳体技术。据称，目前，大陆已研
制出潜艇用、直径9米的超大直径高强度耐压壳体，制成潜艇后将使大陆的战略纵深向外前推1000千米。这种壳体比旧技术提高了几个','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('2','英媒：全欧洲帮中国发展军备 武器禁运无用','0','upload/Content/2013/12/23/5711387742078.jpg','100','','','1','admin','1387742076','1387742028','#f00f00','','1','0','1','2','','资料,中国,早期型,飞豹,战机,曾使用,使用,英国,发动机','资料图：中国早期型飞豹战机曾使用英国发动机。此后全部更换为国产化发动机       　　原标题：英媒：全欧洲帮中国发展军备 武器禁运无用　　英媒：欧洲帮中国升级武器库　　环球时报12月21日报道，英国路透社12月19日报道，原题：中国利用美国重要盟友的技术升级舰船 若人民解放军明天就迎来战争，其武器库中将充满来自德法英等美国最紧密盟友的硬家伙。　　中国多数先进的水面舰船都是由德法设计的发动机驱动。','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('3','日媒：美已无力同时对抗中俄 包围中国终会落空','0','upload/Content/2013/12/23/9531387742206.jpg','100','','','1','admin','1387742206','1387742182','#ED2F8D','','1','0','1','2','','日媒,中俄,联手,拖垮,美国,标题,无力,同时,对抗','日媒：中俄联手能拖垮美国吗       　　原标题：日媒：美已无力同时对抗中俄 包围中国终会落空　　如今通过联手，中俄可确保美国的转向即便落实，仍会效果寥寥。至少眼下，北京和莫斯科搁置领土争端，在战略层面上合作，希望借此将美国逐出亚洲。美国是否有“权”涉足中俄所认定的自家后院，这点我们最好从别处寻求答案。　　日媒：中俄联手能拖垮美国吗　　J·迈克尔·科尔　　日本《外交学者》12月20日文章，原题：','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('4','华媒：南海不是加勒比海 哈格尔批评中国凸显霸道','0','upload/Content/2013/12/23/36481387742234.jpg','102','','','1','admin','1387742233','1387742211','','','1','0','1','2','','中国,航母,编队,模拟,美国,国防部长,哈格尔,格尔,批评','中国航母编队模拟图       　　美国国防部长哈格尔19日批评不久前中国一艘军舰在南海“阻挡”美国导弹巡洋舰的行为，称中方“不负责任”。他宣称美国想在南海和东海“避免所有冲突”，并呼吁中方保持克制。哈格尔没有说，事情发生在中国的家门口，而且是美国军舰追着中国的航母编队走。　　哈格尔的这番指责，把美方对这起事件的反应推向高潮。这与中国方面相对低调得多的反应形成强烈反差，更凸显美国的咄咄逼人。美国在','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('5','女童被同学用改装枪射击 颅内存数百枚金属异物','0','upload/Content/2013/12/23/22541387742468.jpg','101','','','1','admin','1387742467','1387742385','','','1','0','1','3','','光片,显示,小英,脑中,还有,大量,金属,异物,京华时报','X光片显示，小英的脑中还有大量金属异物。京华时报记者谭青摄　　昨天下午，在云南和北京两地的捐助下，9岁女童小英（化名）和家人乘坐火车到达北京，被送往北京大学第一医院接受治疗。12月2日，小英去同学小辉（化名）家中复习功课时，被小辉用家中的改装射钉枪打伤面部，造成大量碎裂的金属异物残留颅内，一度生命垂危。　　京华时报记者王莉霞　　&gt;&gt;事发 　　复习功课时遭同学枪击　　小英家住云南省昆明市','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('6','72岁老人3个月骑行6256公里 途经9个省自治区','0','','100','','','1','admin','1387742566','1387742488','#F09A21','','1','0','1','3','','本报,延吉,记者,张骁,一直,想着,骑着,自行车,走遍','本报延吉讯(记者 张骁) “我一直想着骑着自行车走遍全国，现在就剩下西北没有去过了。”11月22日，途经9个省、自治区，骑行6256公里后，72岁老人金福回到家乡敦化市。他说，自己还不老，计划有机会骑车，再去甘肃、青海看一看。　　金福是敦化市一家酱菜厂的退休工人。金福说，自己年轻时就坚持跑步，从未间断过。2007年，他和朋友一起，骑车游遍东北三省。2010年，又去了海南，两次旅行他积累了不少经验。','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('7','男子下车擦窗 宠物狗窜入车内将车开动撞墙','0','','100','','','1','admin','1387742599','1387742586','#ED2F8D','','1','0','1','3','','近日,民田,先生,记者,讲述了,他曾,遇到,一件,惊险','近日，市民田先生给记者讲述了他曾遇到的一件惊险事：宠物竟然开走了他的车，还险些因此引发事故。这究竟是怎么一回事呢？　　家住大沽街的田先生专门从事宠物犬交易，拥有一家专门饲养宠物犬的宠物基地。他自己饲养的一条杜高犬，当然也是百里挑一的。这条犬不仅长得高大强壮，而且智商颇高。田先生也对它倾注了不少心血，经常开车带它到郊外奔跑玩耍。　　日前，田先生准备开车带爱犬外出郊游。车辆发动后，田先生发现车后侧窗户','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('8','吸毒男子向父母索要毒资未果放火焚家','0','','100','','','1','admin','1387742621','1387742601','','','1','0','1','3','','法制,网讯,记者,小松,见习,马艳,通讯员,陈小勇,小勇','　法制网讯 记者莫小松 见习记者马艳 通讯员陈小勇 
12月19日上午，广西来宾市兴宾区良江镇思贡村的一年轻男子在向父母索钱无果后竟然点火焚烧自家房子，并扬言要杀其父母，还多次向外投掷利器、硬物等东
西阻止救火，后经当地公安、消防等救援人员反复劝说，该男子才“服软”并束手就擒，火灾也随即被扑灭。目前，当地警方已将该男子刑事拘留。　　当日上午11时46分，来宾市119消防调度指挥中心接到报警称：','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('9','加拿大多伦多因冰雨致大面积停电 已断电14小时','0','upload/Content/2013/12/23/29461387742812.jpg','101','','','1','admin','1387742810','1387742694','','','1','0','1','13','','图为,断电,点燃,蜡烛,国际在线,消息,记者,黎萌,当地','　　图为断电后点燃的蜡烛　　国际在线消息(记者 黎萌)：据当地华人刚刚发来的微信称，加拿大多伦多市因冰雨造成大面积停电，已断电14小时。目前局部开始恢复供电，但最晚的恐怕要3天后才能恢复正常。　　“我家用火机点燃煤气取暖，点蜡烛。家里已经很冷了，穿着大棉袄在家猫着呢！我手机要不也早没电了，用手提电脑电池充的。”提供消息的当地华人如此描述。','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('10','莫桑比克官员称致33死空难机长有重大作案嫌疑','0','','100','','','1','admin','1387742836','1387742817','#147ABC','','1','0','1','13','','中新社,约翰,内斯,月日,马普托,消息,莫桑比克,航空,部门','中新社约翰内斯堡12月22日电 马普托消息：莫桑比克航空部门一位负责人21日披露，11月29日坠毁的该国客机的失事原因初步查明，此次空难明显是人为造成，机长有重大的作案嫌疑。　　格林尼治时间11月29日9时26分，这架隶属于莫桑比克航空公司的客机从马普托起飞，目的地是安哥拉首都罗安达。不过，在空中飞行大约两个小
时后，客机在纳米比亚北部地区与总部失去联系。后来经过搜寻，纳米比亚警方发现了失事飞机','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('11','日本福岛1号核电站泄漏1.6吨核污水 原因不明','0','','100','','','1','admin','1387742853','1387742845','','','1','0','1','13','','国际在线,消息,新网,东京,月日,福岛,核电站,运营商,日本','国际在线消息：据俄新网RUSNEWS.CN东京12月22日电，\"福岛\"核电站运营商日本东电公司发布消息说，福岛1号核电站泄漏1.6吨放射性核污水。　　消息说，存储放射性核污水的一个储存罐发生泄漏。随后在泄漏地点安装了抽水阀，而储存罐附近的防护墙周围加固了沙袋。　　污水的辐射水平达到每升560贝克勒尔，放射性锶90达到93贝克勒尔。而允许的标准是每升10贝克勒尔。　　目前尚不清楚','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('12','俄前首富称无心与普京权斗 放弃争夺原公司权益','0','','100','','','1','admin','1387742885','1387742855','','','1','0','1','13','','中新社,柏林,月日,记者,黄霜红,日前,俄罗斯,总统,普京','中新社柏林12月22日电 (记者 黄霜红) 日前被俄罗斯总统普京特赦的前石油巨头霍多尔科夫斯基22日于德国柏林面见媒体时称，他不准备和普京进行权利争斗，并将放弃争夺尤科斯石油公司权益。　　十年前，作为尤科斯石油公司的总裁，霍多尔科夫斯基成为俄罗斯首富。在公开叫板普京并支持反对派之后，霍多尔科夫斯基于2003年被捕，后因偷
税、洗钱及偷盗石油等罪名两次被判入狱，刑期原本至明年8月。本月20日因“人','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('13','资金持续紧期指持仓暗藏乾坤张 短期继续做空','0','upload/Content/2013/12/23/41911387742970.png','100','','','1','admin','1387742969','1387742921','','','1','0','1','5','','热点,栏目,资金,流向,千股,千评,个股,诊断,最新','热点栏目资金流向千股千评个股诊断最新评级模拟交易客户端
	
 	        
        				

	
	
	新浪财经客户端：证监会新政激活A股 IPO改革八大关键词　　《证券市场周刊 红周刊》特约作者 徐世伟　　本周市场延续了上周低迷的表现，沪深300(2278.136, -54.27, -2.33%)指
数以及股指期货持续回落，尤其是周初汇丰PMI初值的回落以及周中国','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('14','央行已连续三天通过SLO投放流动性 累计超3000亿','0','','100','','','1','admin','1387743007','1387742990','#F09A21','','1','0','1','5','','我行,连续,三天,通过,投放,流动性,针对,年末,货币','【我行已连续三天通过SLO投放流动性】针对今年末货币市场出现的新变化，央行已连续三天通过SLO累计向市场注入超过3000亿元流动性，目前银
行体系超额备付已逾1.5万亿元，为历史同期相对较高水平。同时，提示主要商业银行合理调整资产负债结构，提升流动性管理的科学性和前瞻性。　　新浪财经注：什么是SLO？ 　　所谓SLO，是指央行今年年初推出的短期流动性调节工具(英文全称Short-term Liq','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('15','昌九复牌前董事长夜会投资者 跌停厄运再度袭来','0','upload/Content/2013/12/23/53541387743052.png','100','','','1','admin','1387743051','1387743037','','','1','0','1','5','','热点,栏目,资金,流向,千股,千评,个股,诊断,最新','　　　　　　　　　　　　　　　　　　
				

				

    
            
	
	热点栏目资金流向千股千评个股诊断最新评级模拟交易客户端               				

	
	
	新浪财经客户端：证监会新政激活A股 IPO改革八大关键词　　记者 曹丹 张学光 赣州、北京报道　　12月20日，指针已跨过零点，而在江西省赣州市昌九生化(12.50,','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('16','重啤高管离职集团彻底退出 嘉士伯或将全资控股','0','upload/Content/2013/12/23/53651387743081.png','100','','','1','admin','1387743080','1387743068','','','1','0','1','5','','热点,栏目,资金,流向,千股,千评,个股,诊断,最新','热点栏目资金流向千股千评个股诊断最新评级模拟交易客户端        
        				

	
	
	新浪财经客户端：证监会新政激活A股 IPO改革八大关键词　　张明　　2013年12月初股价下跌了20%的重庆啤酒(16.01, -0.24, -1.48%)(600132.SH)
再曝不利信息。12月18日晚间，重庆啤酒发布“治疗用(合成肽)乙型肝炎疫苗”联合用药组《统计分析报','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('17','当年英雄今何在 那些前冠军基金的2013年','0','','100','','','1','admin','1387765883','1387765866','','','1','0','1','6','','编者按,偏股型,基金,年年,证券日报,新闻部,统计,显示,年至','编者按：偏股型基金年年换，《证券日报》基金新闻部统计显示，2007年至2012年年度的偏股型基金，除了华夏大盘在2007年年度和2009年年度勇夺冠军外，其余每年冠军均不一样；而今年，这些昔日夺魁的基金或还是无缘冠军宝座。具体情况如何？我们逐一追踪。　　2012年业绩冠军·景顺长城核心竞争力　　坚守均衡配置 　　今年维持前1/3阵营　　该基金2012年以31.7%的全年回报率，勇夺普通股票型基金冠','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('18','易方达元老陈志民挂靴一拖二 投委会念起空城诀','0','','100','','','1','admin','1387765907','1387765892','','','1','0','1','6','','基金,圈内,人士,分析,市场,相对,海外,投机,氛围','　基金圈内人士分析，A股市场相对海外市场投机氛围浓，投资环境较复杂，而基金相对弱势，这或许陈志民离职的重要原因　　理财周报记者 刘梦/深圳报道　　易方达基金[微博]近日公告，公司副总经理陈志民因个人健康原因提出辞职，并已在12月16日离任。　　关于他“将在手术后转投平安保险”的消息目前并未得到陈志民本人证实。作为分管公募业务的负责人，陈志民在去年3月刚刚被提拔为易方达基金的副总经理。　　陈志民离任','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('19','余额宝不是竞争对手：公募电商化何处去','0','','100','','','1','admin','1387765935','1387765909','#B57E3E','','1','0','1','6','','程亮亮,这是,一个,新的,时代,互联网金融,这个,之前,不显眼','　程亮亮　　这是一个创新的时代，“互联网金融”这个之前并不显眼的词汇，近一年来几乎充斥在每一个财经论坛的主题项中，从业人员开口闭口都在聊着这个话
题。然而，随着被业界称为“互联网金融元年”的2013年即将结束，我们发现，虽然互联网金融在全球范围内以不曾企及的速度高歌猛进，但浮躁的顽疾同样无
处不在。　　作为国内互联网金融的先行者，公募基金在电商化的大潮中到底能分到多少羹？货币基金热潮之后下一步','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('20','华宝添益4倍规模交易揭秘：交易佣金设置为0','0','','100','','','1','admin','1387765958','1387765941','','','1','0','1','6','','华宝,兴业,券商,开展,合作,添益,交易,佣金,设置','华宝兴业与53家券商开展合作，将华宝添益的交易佣金设置为0，可零成本套利　　理财周报记者 李沪生/上海报道　　交易型基金在整个行业并不少见，种类也从最开始的股票型扩展到债券、ETF和分级基金等，但是当交易型基金与货币基金放在一起，将会发生什么样的化学反应？　　让我们来看一组数据，12月9日，华宝兴业现金添益成交量为13.25亿元，10日成交量为15.98亿元，11日暴涨为31.3亿元，13日
再','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('21','苹果公司与中移动达成协议 1月售4G版iPhone','0','upload/Content/2013/12/23/24311387766035.jpg','106','','','1','admin','1387766034','1387765998','#ED2F8D','','1','0','1','8','','年月,上市,新浪,科技,月日,早间,消息,苹果,公司','4G版iPhone 5s及5c明年1月上市　　新浪科技讯 
12月23日早间消息，苹果公司(以下简称苹果)今早宣布与中国移动达成协议，与中国移动在华推出支持移动4G即TD-LTE和移动3G即TD-
SCDMA网络的iPhone手机。包括iPhone 5s和iPhone 
5c，将于明年1月17日上市，并于今年12月25日通过中国移动官网网站和10086热线接受预定。　　苹果2011年承诺推出','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('22','高通8974AC芯片 三星GALAXY S5配置曝光','0','upload/Content/2013/12/23/82141387766060.jpg','100','','','1','admin','1387766059','1387766037','','','1','0','1','8','','据传,三星,将会,年月,正式,发布,不过,目前,没有','　据传三星GALAXY S5将会在明年2月正式发布，不过目前均没有确切的官方消息泄露，按照旗舰机的风格，应该会搭配最顶级的硬件。最近来自安兔兔测试平台的消息，一台型号为SM-G900F的跑分成绩被曝光，很有可能就是三星下一代旗舰机——GALAXY S5。　　搭配高通8974AC处理器　　假如这台三星SM-G900F就是GALAXY S5，那么毫无疑问它将采用高通骁龙800(MSM8974AC)四核','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('23','圣诞专属浪漫 当下最潮情侣手机对对碰','0','upload/Content/2013/12/23/97921387766096.jpg','100','','','1','admin','1387766093','1387766067','#74C0C0','','1','0','1','8','','说起,当下,最潮,时尚,手机,不必,一定,即使,加入','说起当下最潮最时尚的手机，不必多让，那一定是iPhone 5s。即使加入了许多人认为俗气的“土豪金”配色，它实际观感却是淡淡的香槟金色。64位处理器、指纹识别的加入也让你有一种走在科技前沿的极客感，绝对能满足你各方面的需求。点击图片查看iPhone 5s详细资料　　作为搭载iOS 7最先进设备的iPhone 5s，依旧是4英寸的机身，依旧是1136*640的分辨率，手感依旧出色。iPhone  
','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('24','4100万像素万众瞩目 诺基亚1020售3720','0','upload/Content/2013/12/23/86771387766164.jpg','101','','','1','admin','1387766160','1387766111','','','1','0','1','8','','年月日,诺基亚,参数,报价,论坛,软件,行货,发票,今日','2013年12月23日，诺基亚Lumia 1020(参数 报价 论坛 软件)(行货带发票)今日在商家最新报价为3720元。该机配件有：电池(内置)、充电器、耳机、数据线、说明书、保修卡等。诺基亚1020是一款拥有4100万像素镜头的超级拍照3G手机。点击图片查看诺基亚1020详细资料　　诺基亚1020手感极佳，其正面配备有一块4.5英寸的PureMotion 
HD+显示屏，分辨率达到1280X','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('25','读懂狗语：宠物狗思维翻译机问世(图)','0','upload/Content/2013/12/23/27921387766787.jpg','102','','','1','admin','1387766696','1387766678','','','1','0','1','9','','一种,头戴,耳机,原型,可把,思维,模式,变成,人类','一种头戴式耳机原型可把狗的思维模式转变成人类语言。开发人员埃里克-卡尔德隆说：“它看似复杂，其实不然。”开发人员希望最后用这项技术让受伤或残疾的宠物控制假肢或其他设备。　　新浪科技讯 据国外媒体21日报道，很多狗主人会和他们的宠物伙伴建立起一种惊人的亲密关系，但用不了多久，一项原型技术可能让宠物和人的交流达到一个新水平。　　“No More 
Woof”是一种头戴式耳机，通过大脑扫描技术检测狗的','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('26','南极首次发现金伯利岩或蕴藏丰富钻石','0','','100','','','1','admin','1387766828','1387766814','','','1','0','1','9','','新浪,科技,科学美国人,报道,最近,科学家,首次,南极洲,发现','新浪科技讯 据《科学美国人》19日报道，最近科学家首次在南极洲发现一种通常含有钻石的岩石，这暗示着这个被冰雪覆盖的辽阔大陆蕴含着丰富的矿物质。虽然到目前为止研究人员并未在禁止采矿的南极发现钻石，但是他们表示，他们确信这种光彩夺目的宝石就隐藏在那里。　　澳大利亚堪培拉澳大利亚国立大学的格雷格-亚克斯利负责这项研究工作，他说：“如果这些金伯利岩里没有钻石，倒会令人感到非常意外。”一个澳大
利亚科研组','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('27','《自然》评十大科学人物 中国禽流感专家当选','0','upload/Content/2013/12/23/31541387766918.jpg','101','','','1','admin','1387766873','1387766856','#B57E3E','','1','0','1','9','','陈化兰,新华网,伦敦,月日,记者,刘石磊,石磊,英国,自然','陈化兰　　新华网伦敦12月19日电(记者刘石磊)英国《自然》杂志网站18日公布了该刊评出的2013年度全球科学界十大人物，中国禽流感专家陈化兰等人因在各自领域作出突出贡献而当选。　
　这十位年度人物由《自然》杂志编辑选出，每位人物都配有专门的介绍和获选理由。中国国家禽流感参考实验室主任陈化兰名列其中，获选理由是“帮助中国平息
H7N9禽流感疫情”，《自然》将她称为“战斗在前线的‘流感侦探’”。','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('28','好奇号首次测定火星地表岩石年龄：约40亿年','0','','100','','','1','admin','1387767012','1387766981','','','1','0','1','9','','这张,示意图,展示,理论上,认为,古代,盖尔,陨坑,内部','这张示意图展示的是理论上认为古代盖尔陨坑内部曾经存在的一个湖泊的形态　　这是根据好奇号搭载的辐射评估探测器(RAD)获得数据与其他各种情形下的辐射剂量进行对比的示意。这一结果对于未来载人登陆火星的计划具有重要参考价值　　新浪科技讯 北京时间12月20日消息，据美国宇航局好奇号项目官网报道，近日好奇号项目组接连在《科学》杂志上发表文章，报告了一系列重要的进展。好奇号在火星的工作正为科学家们提供窥视火','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('29','这才叫硬汉！血泪啊！曼城领袖一张图太铁血太悲壮','0','','100','','','1','admin','1387767867','1387767375','#f00f00','','1','0','1','11','','新浪,体育,领先,大好形势,之下,连追两,扳平,比分,幸好','新浪体育讯　2比0领先的大好形势之下被连追两球扳平比分，幸好下半场纳瓦斯临危受命奉献了一粒精彩的进球，又再一次将比分超出，最终，曼城[微博][微博]人在客场有惊无险的以4比2的比分击败了富勒姆，与榜首利物浦[微博]的积分差距缩小到了1分。进球视频-孔帕尼诡异摆乌龙 掩面沉默黯然神伤媒体来源：新浪体育　　而曼城队长孔帕尼[微博]无
疑就是半场比赛的风云人物了，他上半场的一脚近距离的射门为曼城将比分','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('30','扇脸博阿斯！英超黑又硬怒吼报复 兰帕德也如此被打压','0','','100','','','1','admin','1387767901','1387767868','','','1','0','1','11','','新浪,体育,阿斯,课后,一直,葡萄牙,少帅,打压,德巴','新浪体育讯　博阿斯下课后，一直被葡萄牙少帅打压的阿德巴就立刻就迎来了爆发。在热刺[微博]3-2战胜南安普顿的比赛中，多哥前锋梅开二度帮助热刺逆转获得了一场重要胜利。　　本赛季，阿德巴约在博阿斯手下的处境非常糟糕。因为与葡萄牙少帅不和，他曾被罚与球队青年球员一起训练。《每日邮报》在谈及此事时曾表示，对于博阿斯的这一行为，阿德巴约怕是永远都不会原谅他的。在博阿斯下课前，阿德巴约只在球队0-6被曼城[微','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('31','欧洲第1神!12场24球脚踩C罗 正式标价1亿皇马来砸','0','','100','','','1','admin','1387767935','1387767902','#f00f00','','1','0','1','11','','新浪,体育,只有,埃弗拉,弗拉,伊万,诺维奇,能够,阻挡','新浪体育讯　“只有埃弗拉和伊万诺维奇能够阻挡苏亚雷斯。”这是球迷们在看过乌拉圭神锋势不可挡的表现后调侃出的结论。的确，以如今“杀红眼”的苏亚雷斯的状态，除非再造出一轮禁赛风波，否则地球人已经无法阻挡这名利物浦[微博]杀神进球的步伐了。视频-梅开二度&无私助攻 无解苏神V卡迪夫个人集锦媒体来源：新浪体育　　就在利物浦与卡迪夫城一战前，苏亚雷斯与红军完成了续约，通过这份长达4年半的合约，苏亚雷','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('32','皮队:失去大洛是很大打击 基德:还没定谁替他先发','0','','100','','','1','admin','1387768014','1387767941','#ED2F8D','','1','0','1','12','','新浪,体育,北京时间,月日,新泽西,当地时间,上午,篮网,训练','　新浪体育讯　北京时间12月23日，新泽西当地时间12月22日上午11点，篮网在新泽西训练中心进行日常训练。中锋布鲁克－洛佩斯由于在周五对76人比赛中受伤，右脚第五趾骨骨折，没有参加训练，今天篮网官方确认其赛季报销。　　这赛季开赛以来篮网一直遭受伤病困扰，球队的主力都因不同程度的伤病，德隆-威廉姆斯、保罗-皮尔斯[微博]、杰森-特里与安德烈-基里连科都曾缺席多场比赛，其中，特里和基里连科至今仍然没','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('33','全明星科比书豪得票虚高? 专家:看看威少利拉德吧','0','','100','','','1','admin','1387768036','1387768015','#f00f00','','1','0','1','12','','新浪,体育,北京时间,月日,消息,据报道,年全,明星,投票','﻿新浪体育讯　北京时间12月23日消息，据xnsports报道，2014年NBA全明星投票首轮结果已经放出，xnsports专家韦德[微博]-埃文森对这一结果进行了点评，他认为科比[微博]-布莱恩特、德里克-罗斯[微博]、布雷克-格里芬[微博]、林书豪[微博]、凯文-加内特[微博]等人的得票率都太高了。　　全明星票选首轮结果，林书豪在西区后卫球员中得票率第四，仅次于科比，克里斯-保罗[微博]和斯蒂','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('34','伯德：不会主动交易格兰杰 本赛季他将一直任替补','0','','109','','','1','admin','1387768055','1387768037','','','1','0','1','12','','新浪,体育,北京时间,月日,印第安纳星报,报道,丹尼,格兰,杰伤','新浪体育讯　北京时间12月23日，据《印第安纳星报》报道，在丹尼-格兰杰伤停期间，关于他的交易流言时有传出。如今他已经正式复出，步行者方面也表明了自己的立场，球队总裁拉里-伯德在近日接受采访时表示，他不会主动寻求交易格兰杰的可能。　　“我和丹尼以及他的经纪人都谈过了，我不会寻求将他交易出去。”伯德说道，“但你永远不知道未来会发生什么。如果有合适的交易方案出现并且能够帮助到球队，那么我会认真考虑的。','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('35','威少坚信雷霆是联盟最佳 KD：球传起来我们就很好','0','','100','','','1','admin','1387768078','1387768056','','','1','0','1','12','','新浪,体育,北京时间,月日,雷霆,战胜,马刺,得了,一波','新浪体育讯　北京时间12月23日，雷霆战胜马刺，取得了一波9连胜，这是联盟目前球队最长的连胜纪录，同时也让他们成为了目前联盟中胜率最高的球队。雷霆核心拉塞尔-威斯布鲁克[微博]就表示，他认为，雷霆现在是联盟当中最好的球队。　　“我们有联盟最好的战绩，我相信，我们是最好的球队，不管别人说着说那的，”威少说，“你必须上场打球，你可以去预测任何东西，但是你必须要去面对比赛。”　　雷霆在昨天战胜了他们的老','')");
$db->exe("REPLACE INTO ".$db_prefix."content (`aid`,`title`,`new_window`,`thumb`,`click`,`source`,`redirecturl`,`allowreply`,`username`,`addtime`,`updatetime`,`color`,`template`,`ishtml`,`arc_sort`,`status`,`cid`,`seo_title`,`keywords`,`description`,`html_path`) VALUES('36','枪手vs切尔西前瞻：榜首大战 狂人对教授不败','0','upload/Content/2013/12/23/99211387801035.jpg','100','','','1','admin','1387801035','1387757806','','','1','0','1','12','','切尔西,官方,微博,数据,赛季,已经,胜过,枪手,腾讯','切尔西(官方微博 数据)本赛季已经2-0战胜过枪手腾讯体育讯 北京时间12月24日凌晨4点，英超(微博 专题) 第17轮迎来一场强强对话，阿森纳(官方微博 官网 数据 )将坐镇酋长球场与来访的切尔西进行榜首大战，两队目前只有2分的分差。腾讯体育将对本场比赛进行图文直播，敬请关注！比赛看点：枪手蓝军榜首大战：前16轮联赛中阿森纳以35分领跑，切尔西虽然排在第3位，但与枪手的分差却只有2分，因此这场比','')");
