<?php if(!defined('HDPHP_PATH'))EXIT;
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('19','后盾','3')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('20','课堂','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('21','一元','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('22','开课','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('23','欣喜','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('24','备感','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('25','一期','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('26','成功','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('27','支持','2')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('10','全面','1')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('11','德智体','1')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('13','发展','1')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('14','中国','1')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('15','程序员','1')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('16','顶尖','1')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('17','围观','1')");
$db->exe("REPLACE INTO ".$db_prefix."tag (`tid`,`tag_name`,`total`) VALUES('18','快来','1')");
