<?php if (!defined('HDPHP_PATH')) exit; 
return array (
  'WEBNAME' => 'HDCMS内容管理系统',
  'EMAIL_FORMMAIL' => '后盾网',
  'CREATE_INDEX_HTML' => '1',
  'EMAIL_USERNAME' => 'houdunwang@houdunwang.com',
  'MEMBER_EMAIL_VALIDATE' => '0',
  'HTML_PATH' => 'h',
  'EMAIL_PASSWORD' => 'admin888',
  'KEYWORDS' => 'php培训,php实训,后盾网',
  'ICP' => '京ICP备12048441号-3',
  'COPYRIGHT' => 'Copyright © 2012-2014 HDCMS 后盾网',
  'DESCRIPTION' => '后盾网顶尖PHP培训 内容全面 全程实战!业内顶级讲师亲自授课,千余课时独家视频教程免费下载,超百G原创视频资源,实力不容造假!010-64825057',
  'BACKUP_DIR' => 'backup',
  'WEB_OPEN' => '1',
  'UPLOAD_PATH' => 'upload',
  'ALLOW_TYPE' => 'jpg,jpeg,png,bmp,gif,zip,rar,doc',
  'ALLOW_SIZE' => '10480000',
  'WATER_ON' => '1',
  'WATER_TEXT' => 'houdunwang.com',
  'WATER_TEXT_SIZE' => '16',
  'WATER_IMG' => 'HDCMS/Static/image/water.png',
  'WATER_PCT' => '80',
  'WATER_QUALITY' => '90',
  'WATER_POS' => '9',
  'DEL_CONTENT_MODEL' => '0',
  'DOWN_REMOTE_PIC' => '0',
  'AUTO_DESC' => '1',
  'AUTO_THUMB' => '1',
  'MEMBER_OPEN' => '1',
  'WEB_CLOSE_MESSAGE' => '网站维护中，请稍候访问...',
  'WEB_STYLE' => 'default',
  'INIT_CREDITS' => '100',
  'INDEX_CACHE_TIME' => '-1',
  'CATEGORY_CACHE_TIME' => '-1',
  'CONTENT_CACHE_TIME' => '-1',
  'URL_REWRITE' => '0',
  'EMAIL_HOST' => 'smtp.exmail.qq.com',
  'EMAIL_PORT' => '25',
  'EMAIL_FROMNAME' => '后盾网',
);
?>