<?php if(!defined('HDPHP_PATH'))EXIT;
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('1','1','1','textarea','1','content','description','描述','','1','1','19','a:3:{s:5:\"width\";s:3:\"500\";s:6:\"height\";s:3:\"100\";s:7:\"default\";s:0:\"\";}','','0','','','0','','0','1','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('2','1','1','input','1','content','keywords','关键字','','1','1','18','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('3','1','1','number','1','content','arc_sort','排序','','1','1','100','a:5:{s:10:\"field_type\";s:9:\"mediumint\";s:11:\"num_integer\";s:1:\"6\";s:11:\"num_decimal\";s:1:\"2\";s:4:\"size\";s:3:\"150\";s:7:\"default\";s:3:\"100\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('4','1','1','box','1','content','url_type','文章访问方式','','1','1','100','a:3:{s:7:\"options\";s:45:\"1|静态访问,2|动态访问 ,3|继承栏目\";s:9:\"form_type\";s:5:\"radio\";s:7:\"default\";s:1:\"3\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('5','1','1','tag','1','content','tag','tag','','1','1','17','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('6','1','1','datetime','1','content','addtime','添加时间','','1','1','25','a:1:{s:6:\"format\";s:1:\"1\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('7','1','1','template','1','content','template','模板','','1','1','100','','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('8','1','1','input','1','content','redirecturl','转向链接','','1','1','21','a:3:{s:4:\"size\";s:3:\"150\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','/^http:///','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('9','1','1','cid','1','content','cid','栏目','','1','1','2','','','0','','','0','','0','1','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('10','1','1','input','1','content','source','来源','','1','1','26','a:3:{s:4:\"size\";s:3:\"150\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('11','1','1','thumb','1','content','thumb','缩略图','','1','1','20','','','0','','','0','','0','0','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('12','1','1','flag','1','content','flag','属性','','1','1','12','','','0','','','0','','0','1','1','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('13','1','1','input','1','content','seo_title','SEO标题','','1','1','13','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('14','1','1','input','1','content','html_path','html文件名','','1','1','100','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('15','1','1','title','1','content','title','标题','','1','1','1','a:2:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";}','','0','100','','1','','0','1','1','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('16','1','1','content','2','content_data','content','正文','','1','1','14','','','0','','','0','','0','1','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('17','1','1','number','1','content','click','点击数','','1','1','100','a:4:{s:11:\"num_integer\";s:1:\"6\";s:11:\"num_decimal\";s:1:\"2\";s:4:\"size\";s:3:\"150\";s:7:\"default\";s:3:\"100\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('68','4','1','number','1','a','click','点击数','','1','1','100','a:4:{s:11:\"num_integer\";s:1:\"6\";s:11:\"num_decimal\";s:1:\"2\";s:4:\"size\";s:3:\"150\";s:7:\"default\";s:3:\"100\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('67','4','1','content','2','a_data','content','正文','','1','1','14','','','0','','','0','','0','1','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('52','4','1','title','1','a','title','标题','','1','1','1','a:2:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";}','','0','100','','1','','0','1','1','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('53','4','1','input','1','a','html_path','html文件名','','1','1','100','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('54','4','1','flag','1','a','flag','属性','','1','1','12','','','0','','','0','','0','1','1','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('55','4','1','input','1','a','seo_title','SEO标题','','1','1','13','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('56','4','1','thumb','1','a','thumb','缩略图','','1','1','20','','','0','','','0','','0','0','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('57','4','1','cid','1','a','cid','栏目','','1','1','2','','','0','','','0','','0','1','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('58','4','1','input','1','a','source','来源','','1','1','26','a:3:{s:4:\"size\";s:3:\"150\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('59','4','1','input','1','a','redirecturl','转向链接','','1','1','21','a:3:{s:4:\"size\";s:3:\"150\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','/^http:///','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('60','4','1','datetime','1','a','addtime','添加时间','','1','1','25','a:1:{s:6:\"format\";s:1:\"1\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('61','4','1','template','1','a','template','模板','','1','1','100','','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('62','4','1','tag','1','a','tag','tag','','1','1','17','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('63','4','1','box','1','a','url_type','文章访问方式','','1','1','100','a:3:{s:7:\"options\";s:45:\"1|静态访问,2|动态访问 ,3|继承栏目\";s:9:\"form_type\";s:5:\"radio\";s:7:\"default\";s:1:\"3\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('64','4','1','number','1','a','arc_sort','排序','','1','1','100','a:5:{s:10:\"field_type\";s:9:\"mediumint\";s:11:\"num_integer\";s:1:\"6\";s:11:\"num_decimal\";s:1:\"2\";s:4:\"size\";s:3:\"150\";s:7:\"default\";s:3:\"100\";}','','0','','','0','','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('65','4','1','input','1','a','keywords','关键字','','1','1','18','a:3:{s:4:\"size\";s:3:\"300\";s:7:\"default\";s:0:\"\";s:8:\"ispasswd\";s:1:\"0\";}','','0','','','0','','0','1','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."field (`fid`,`mid`,`status`,`field_type`,`table_type`,`table_name`,`field_name`,`title`,`tips`,`enable`,`is_system`,`fieldsort`,`set`,`css`,`minlength`,`maxlength`,`validate`,`required`,`error`,`isunique`,`isbase`,`issearch`,`isadd`)
						VALUES('66','4','1','textarea','1','a','description','描述','','1','1','19','a:3:{s:5:\"width\";s:3:\"500\";s:6:\"height\";s:3:\"100\";s:7:\"default\";s:0:\"\";}','','0','','','0','','0','1','0','1')");
