<?php if(!defined('HDPHP_PATH'))EXIT;
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('1','1','1','0','0','0','0','0','0','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('2','1','1','0','0','0','0','0','0','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('3','1','1','0','0','0','0','0','0','0','1')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('4','1','1','0','0','0','0','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('5','1','1','0','0','0','0','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('6','1','1','0','0','0','0','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('7','1','1','0','0','0','0','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('8','1','1','0','0','0','0','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('9','1','1','0','0','0','0','0','0','0','0')");
$db->exe("REPLACE INTO ".$db_prefix."category_access (`rid`,`cid`,`mid`,`show`,`add`,`edit`,`del`,`order`,`move`,`audit`,`admin`) VALUES('10','1','1','0','0','0','0','0','0','0','0')");
